steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.9.8'
    script: terraform init
  - id: 'terraform plan'
    name: 'hashicorp/terraform:1.9.8'
    script: terraform plan
  - id: 'terraform apply'
    name: 'hashicorp/terraform:1.9.8'
    script: terraform apply --auto-approve

artifacts:
  objects:
    location: 'gs://gke-state-tf-poc-1/terraform/cloudbuild/apply/${BUILD_ID}'
    paths: ['cloudbuild-tf-apply.yaml', 'tmp_plan/*.tfplan']
