steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['build', ...]
logsBucket: gs://gke-state-tf-poc-1/
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform:1.9.8'
    script: terraform init
  - id: 'terraform plan'
    name: 'hashicorp/terraform:1.9.8'
    script: terraform plan
  - id: 'terraform apply'
    name: 'hashicorp/terraform:1.9.8'
    script: terraform apply --auto-approve
